server:
  port: 8766
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: consumer
    api-b:
      path: /api-b/**
      serviceId: feign